### ISSUE TITLE
Is this suitable for running over multiple HTTP request cycles?

### ISSUE THREAD

**Issue by AndrewCarterUK** [Ocramius/PSR7Session#26]
Hello,

I work on a project called [PHPFastCGI](http://github.com/PHPFastCGI/FastCGIDaemon) and I've been keeping an eye out for PSR-7 session middleware to recommend for the project.

Most that I've seen makes the assumption that it will only ever be used for one request cycle - is the same true for this one?

Best Regards,

Andrew

**Comment by Ocramius** [comment]
@AndrewCarterUK yes, that was one of the design prerequisites.

**Comment by AndrewCarterUK** [comment]
Awesome, I'll add it to the docs later :) (Y)

**Comment by lcobucci** [comment]
We also have a [test covering that](https://github.com/Ocramius/PSR7Session/blob/master/test/PSR7SessionTest/Http/SessionMiddlewareTest.php#L76) :smile:
