### ISSUE TITLE
Signing key in the README doesn't have enough entropy

### ISSUE THREAD

**Issue by AndrewCarterUK** [Ocramius/PSR7Session#34]
I've got a [pull request](https://github.com/thephpleague/glide/pull/109) open on a League Package which that adds a vendor binary to the package for generating a secure key.

I'm wondering whether it's worth splitting this up to be it's own package that can be used on a global composer install?

**Comment by AndrewCarterUK** [comment]
I've made a tool for doing this, not sure if you want me to create a pull request for including it: https://github.com/AndrewCarterUK/CryptoKey

**Comment by Ocramius** [comment]
@AndrewCarterUK while this is true, it is documented that the keys should be generated properly.
This package is not supposed to take on that bit, but I'd gladly merge a PR that links to some more clear and complete docs about key generation.

**Comment by Ocramius** [comment]
Or are you suggesting to add a `::fromAutoGeneratedKey()`?

**Comment by AndrewCarterUK** [comment]
I'm just suggesting that it's made clear to users that mashing something such as:

```php
$app->pipe(\PSR7Session\Http\SessionMiddleware::fromSymmetricKeyDefaults(
    's3ssionp4ssword',
    1200 // 20 minutes
));
```

Isn't secure enough for this purpose.

At the moment it looks a little bit like a place to type a password rather than something to fill with lots of bits straight out of a CSPRNG.

**Comment by Ocramius** [comment]
Ah yes. This is made clear in the docs, but feel free to add a link and a
warning also to the README

**Comment by AndrewCarterUK** [comment]
I've got two open pull requests (both take it or leave it) - happy to edit them in any way you feel is appropriate.

https://github.com/Ocramius/PSR7Session/pull/35
https://github.com/Ocramius/PSR7Session/pull/36

**Comment by AndrewCarterUK** [comment]
Closed by https://github.com/Ocramius/PSR7Session/pull/36
