### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by egil-systems** [Ocramius/PSR7Session#47]
Just an heads up with regard to versions / composer etc:

1. composer create-project zendframework/zend-expressive-skeleton test-sessions
2. cd test-sessions
3. composer require ocramius/psr7-session

Step 3 doesn't complete with the following output:

Using version ^1.0 for ocramius/psr7-session
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ocramius/proxy-manager == 2.0.1.0 could not be found.
  Problem 2
    - The requested package filp/whoops == 2.0.0.0 could not be found.
  Problem 3
    - zendframework/zend-code 2.4.9 requires zendframework/zend-eventmanager 2.4.9 -> satisfiable by zendframework/zend-eventmanager[2.4.9].
    - zendframework/zend-code 2.4.8 requires zendframework/zend-eventmanager 2.4.8 -> satisfiable by zendframework/zend-eventmanager[2.4.8].
    - zendframework/zend-code 2.4.7 requires zendframework/zend-eventmanager 2.4.7 -> satisfiable by zendframework/zend-eventmanager[2.4.7].
    - zendframework/zend-code 2.4.6 requires zendframework/zend-eventmanager 2.4.6 -> satisfiable by zendframework/zend-eventmanager[2.4.6].
    - zendframework/zend-code 2.4.5 requires zendframework/zend-eventmanager 2.4.5 -> satisfiable by zendframework/zend-eventmanager[2.4.5].
    - zendframework/zend-code 2.4.4 requires zendframework/zend-eventmanager 2.4.4 -> satisfiable by zendframework/zend-eventmanager[2.4.4].
    - zendframework/zend-code 2.4.3 requires zendframework/zend-eventmanager 2.4.3 -> satisfiable by zendframework/zend-eventmanager[2.4.3].
    - zendframework/zend-code 2.4.2 requires zendframework/zend-eventmanager 2.4.2 -> satisfiable by zendframework/zend-eventmanager[2.4.2].
    - zendframework/zend-code 2.4.1 requires zendframework/zend-eventmanager 2.4.1 -> satisfiable by zendframework/zend-eventmanager[2.4.1].
    - zendframework/zend-code 2.4.0 requires zendframework/zend-eventmanager 2.4.0 -> satisfiable by zendframework/zend-eventmanager[2.4.0].
    - zendframework/zend-code 2.3.9 requires zendframework/zend-eventmanager 2.3.9 -> satisfiable by zendframework/zend-eventmanager[2.3.9].
    - zendframework/zend-code 2.3.8 requires zendframework/zend-eventmanager 2.3.8 -> satisfiable by zendframework/zend-eventmanager[2.3.8].
    - zendframework/zend-code 2.3.7 requires zendframework/zend-eventmanager 2.3.7 -> satisfiable by zendframework/zend-eventmanager[2.3.7].
    - zendframework/zend-code 2.3.6 requires zendframework/zend-eventmanager 2.3.6 -> satisfiable by zendframework/zend-eventmanager[2.3.6].
    - zendframework/zend-code 2.3.5 requires zendframework/zend-eventmanager 2.3.5 -> satisfiable by zendframework/zend-eventmanager[2.3.5].
    - zendframework/zend-code 2.3.4 requires zendframework/zend-eventmanager 2.3.4 -> satisfiable by zendframework/zend-eventmanager[2.3.4].
    - zendframework/zend-code 2.3.3 requires zendframework/zend-eventmanager 2.3.3 -> satisfiable by zendframework/zend-eventmanager[2.3.3].
    - zendframework/zend-code 2.3.2 requires zendframework/zend-eventmanager 2.3.2 -> satisfiable by zendframework/zend-eventmanager[2.3.2].
    - zendframework/zend-code 2.3.1 requires zendframework/zend-eventmanager 2.3.1 -> satisfiable by zendframework/zend-eventmanager[2.3.1].
    - zendframework/zend-code 2.3.0 requires zendframework/zend-eventmanager 2.3.0 -> satisfiable by zendframework/zend-eventmanager[2.3.0].
    - zendframework/zend-code 2.2.9 requires zendframework/zend-eventmanager 2.2.9 -> satisfiable by zendframework/zend-eventmanager[2.2.9].
    - zendframework/zend-code 2.2.8 requires zendframework/zend-eventmanager 2.2.8 -> satisfiable by zendframework/zend-eventmanager[2.2.8].
    - zendframework/zend-code 2.2.7 requires zendframework/zend-eventmanager 2.2.7 -> satisfiable by zendframework/zend-eventmanager[2.2.7].
    - zendframework/zend-code 2.2.6 requires zendframework/zend-eventmanager 2.2.6 -> satisfiable by zendframework/zend-eventmanager[2.2.6].
    - zendframework/zend-code 2.2.10 requires zendframework/zend-eventmanager 2.2.10 -> satisfiable by zendframework/zend-eventmanager[2.2.10].
    - zendframework/zend-eventmanager 2.5.0 requires zendframework/zend-stdlib ~2.5.0 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.9 requires zendframework/zend-stdlib 2.4.9 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.8 requires zendframework/zend-stdlib 2.4.8 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.7 requires zendframework/zend-stdlib 2.4.7 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.6 requires zendframework/zend-stdlib 2.4.6 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.5 requires zendframework/zend-stdlib 2.4.5 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.4 requires zendframework/zend-stdlib 2.4.4 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.3 requires zendframework/zend-stdlib 2.4.3 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.2 requires zendframework/zend-stdlib 2.4.2 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.1 requires zendframework/zend-stdlib 2.4.1 -> no matching package found.
    - zendframework/zend-eventmanager 2.4.0 requires zendframework/zend-stdlib 2.4.0 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.9 requires zendframework/zend-stdlib 2.3.9 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.8 requires zendframework/zend-stdlib 2.3.8 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.7 requires zendframework/zend-stdlib 2.3.7 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.6 requires zendframework/zend-stdlib 2.3.6 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.5 requires zendframework/zend-stdlib 2.3.5 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.4 requires zendframework/zend-stdlib 2.3.4 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.3 requires zendframework/zend-stdlib 2.3.3 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.2 requires zendframework/zend-stdlib 2.3.2 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.1 requires zendframework/zend-stdlib 2.3.1 -> no matching package found.
    - zendframework/zend-eventmanager 2.3.0 requires zendframework/zend-stdlib 2.3.0 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.9 requires zendframework/zend-stdlib 2.2.9 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.8 requires zendframework/zend-stdlib 2.2.8 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.7 requires zendframework/zend-stdlib 2.2.7 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.6 requires zendframework/zend-stdlib 2.2.6 -> no matching package found.
    - zendframework/zend-eventmanager 2.2.10 requires zendframework/zend-stdlib 2.2.10 -> no matching package found.
    - zendframework/zend-eventmanager 2.6.0 requires athletic/athletic dev-master -> no matching package found.
    - Conclusion: don't install ocramius/proxy-manager 1.0.2
    - Conclusion: don't install ocramius/proxy-manager 1.0.1
    - Conclusion: remove zendframework/zend-eventmanager 3.0.1
    - Conclusion: don't install zendframework/zend-eventmanager 3.0.1
    - zendframework/zend-code 2.5.3 requires zendframework/zend-eventmanager ~2.5 -> satisfiable by zendframework/zend-eventmanager[2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3].
    - zendframework/zend-code 2.5.2 requires zendframework/zend-eventmanager ~2.5 -> satisfiable by zendframework/zend-eventmanager[2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3].
    - zendframework/zend-code 2.5.1 requires zendframework/zend-eventmanager ~2.5 -> satisfiable by zendframework/zend-eventmanager[2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3].
    - zendframework/zend-code 2.5.0 requires zendframework/zend-eventmanager ~2.5.0 -> satisfiable by zendframework/zend-eventmanager[2.5.0, 2.5.1, 2.5.2].
    - Can only install one of: zendframework/zend-eventmanager[2.6.1, 3.0.1].
    - Can only install one of: zendframework/zend-eventmanager[2.6.2, 3.0.1].
    - Can only install one of: zendframework/zend-eventmanager[2.6.3, 3.0.1].
    - Can only install one of: zendframework/zend-eventmanager[2.5.1, 3.0.1].
    - Can only install one of: zendframework/zend-eventmanager[2.5.2, 3.0.1].
    - Conclusion: don't install zendframework/zend-code 3.0.1|install zendframework/zend-code 2.5.0|install zendframework/zend-code 2.5.1|install zendframework/zend-code 2.5.2|install zendframework/zend-code 2.5.3
    - Installation request for zendframework/zend-eventmanager == 3.0.1.0 -> satisfiable by zendframework/zend-eventmanager[3.0.1].
    - Installation request for ocramius/proxy-manager ^1.0 -> satisfiable by ocramius/proxy-manager[1.0.0, 1.0.1, 1.0.2].
    - Conclusion: remove zendframework/zend-code 3.0.1|install zendframework/zend-code 2.5.0|install zendframework/zend-code 2.5.1|install zendframework/zend-code 2.5.2|install zendframework/zend-code 2.5.3
    - ocramius/proxy-manager 1.0.0 requires zendframework/zend-code >2.2.5,<3.0 -> satisfiable by zendframework/zend-code[2.2.10, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2].
    - Can only install one of: zendframework/zend-code[2.6.0, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.6.1, 3.0.1].
    - Can only install one of: zendframework/zend-code[2.6.2, 3.0.1].
    - Installation request for zendframework/zend-code == 3.0.1.0 -> satisfiable by zendframework/zend-code[3.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

My guess is that zend expressive is setting up composer with dependency of versions that is not compatible with psr7-sessions.

**Comment by lferro9000** [comment]
Hi again,

After changing all composer branches to "*@dev" (which is not the recommended thing to do), do a composer update and then:

composer require ocramius/psr7-session

It installs fine.

My guess here is that the correct behavior for a middleware is to, ideally, to be installable against the "reference implementation" of the framework (in this case, the base skeleton app from zend expressive).

Sorry if i sound a bit oppiniated, but my believe is that all reference middleware (like this one) should "just work" :)

Thank you all for the work on psr7 stuff, it really is making a difference!

Cheers,
LF

**Comment by Ocramius** [comment]
This seems to be a problem with ` zendframework/zend-expressive-skeleton`, not with this package. 

To demonstrate it, you will see that following actually works:

```sh
composer create-project zendframework/zend-expressive-skeleton test-sessions
cd test-sessions
composer update # this was added, but shows that the problem is not in this package
composer require ocramius/psr7-session # now works
```

Please report the issue in https://github.com/zendframework/zend-expressive-skeleton/issues

Closing as invalid.

**Comment by lferro9000** [comment]
Will do, sorry to waste your time :)
